### ISSUE TITLE
USER STORY: User can provide feedback anonymously

### ISSUE THREAD

**Issue by bojaymes** [bojaymes/My-First-Agile-Project#7]
## User Story:
In order to **provide feedback** as a **yoga4mom community user**, I can choose to **hide my identity when providing my feedback**

## Acceptance Criteria:
- The checkbox for anonymous should appear below the feedback box
- The checkbox is not selected by default
- The submit box should appear under the checkbox
- After submitting, the default submission confirmation should be adjusted to include the username

## Tasks:

- [ ] Create a checkbox (not marked by default) for user to hide their identity after providing feedback
- [ ] Create a submit button under the checkbox for user to submit inputs
- [ ] Display a message "Your poll and feedback has been received"
- [ ] Test the completed functionality
